In [ ]:
print("subhansh Dwivedi")


subhansh Dwivedi


In [ ]:
num=[10,23,45,43]
print(num)
print(type(num))

[10, 23, 45, 43]
<class 'list'>


In [ ]:
import numpy as np
arr=np.array([1,2,3,4],dtpye=np.float32)
print(arr,arr.dtyo

TypeError: array() got an unexpected keyword argument 'dtpye'

In [ ]:
import numpy as np


In [7]:
# Input
lst = [5, 10, 0, 200]
# Expected Output:
# [10, 15, 5, 20}
import numpy as np
arr = np.array(lst)
print(arr +5 )

[ 10  15   5 205]


In [13]:
lst = [1, 2, 3, 'text', True, 3+2j]   
import numpy as np
arr = np.array(lst)
print(type(arr[0]),type(arr[4]),type(arr[5]))

<class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'>


In [14]:
 # Input
lst = [56, 45, 12, 6] 
# Expected output:
# 16 
import numpy as np
arr = np.array(lst)
print(arr.nbytes)


16


In [34]:
import numpy as np
# arr=np.array([19,33,45,39,64,23],dtype=int)
# print(arr)
# print(type(arr))
# print(np.result_type(arr))
# print(np.linspace(0, 160, 5, dtype = np.float64))
# print(np.array([23,45,64,342,23,4,55,55]).reshape(2,4))
print(np.matrix([[24,32,32,34,55],
                 [43,4,32,0,0]]))


[[24 32 32 34 55]
 [43  4 32  0  0]]


In [48]:
import numpy as np
print(np.ones( (3,3), dtype = np.float64 ))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
